name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Package
        run: |
          rm -rf obsidian-plugin-proxy.tar.gz
          mv dist obsidian-plugin-proxy
          tar -czf obsidian-plugin-proxy.tar.gz obsidian-plugin-proxy/main.js obsidian-plugin-proxy/manifest.json obsidian-plugin-proxy/data.json

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          body: "发布版本"
          prerelease: false
          files: obsidian-plugin-proxy.tar.gz
          token: ${{secrets.TOKEN}}
